language: node_js
node_js:
  - "10"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo down root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"